### ISSUE TITLE
No releases even though there used to be

### ISSUE THREAD

**Issue by guysoft** [jerash/jpmidi#4]
Hey,
Since http://juliencoder.de/jpmidi/jpmidi-0.2.tar.gz is broken now, how about adding a release?

Also see:
https://github.com/zynthian/zynthian-sys/issues/24

**Comment by jerash** [comment]
@guysoft thanks for the notice, indeed this should be needed
 I'm looking a how to do it here in github since I never needed to.

**Comment by jerash** [comment]
new release available here : https://github.com/jerash/jpmidi/archive/v0.21.tar.gz
